AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - './*'
    - 'bin/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

####################################
## Customization for this project ##
####################################

MethodLength:
  Max: 20

Lint/MissingSuper:
  Enabled: false

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

SymbolArray:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

PredicateName:
  Enabled: false

MultilineIfModifier:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

IfUnlessModifier:
  Enabled: false

StringLiterals:
  Enabled: false

TrailingCommaInArrayLiteral:
  Enabled: false

TrailingCommaInHashLiteral:
  Enabled: false

TrailingCommaInArguments:
  Enabled: false

MultilineMethodCallIndentation:
  Enabled: false

EmptyLineAfterGuardClause:
  Enabled: false

RescuedExceptionsVariableName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
